#helm install filebeat elastic/filebeat -f values.yaml 
# namespace: log
---
replicas: 1
readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        curl --fail 127.0.0.1:5066
daemonset:
  enabled: true
  # extraEnvs: 
  # - name: ELASTICSEARCH_HOST
  #   value: elasticsearch-master.db
  # - name: ELASTICSEARCH_PORT
  #   value: "9200"
  # - name: ELASTICSEARCH_USERNAME
  #   value: elastic
  # - name: ELASTICSEARCH_PASSWORD
  #   value: changeme
  # - name: ELASTIC_CLOUD_ID
  #   value:
  # - name: ELASTIC_CLOUD_AUTH
  #   value:
  filebeatConfig:
    filebeat.yml: |-
      filebeat.config:
        prospectors:
          # Mounted `filebeat-prospectors` configmap:
          path: ${path.config}/prospectors.d/*.yml
          # Reload prospectors configs as they change:
          reload.enabled: false
        modules:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload.enabled: false
      processors:
      - add_cloud_metadata:

      cloud.id: ${ELASTIC_CLOUD_ID}
      cloud.auth: ${ELASTIC_CLOUD_AUTH}

      output.logstash:
        hosts: ['logstash-logstash:5044']
  # hostNetworking: true
deployment:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: tcp
        max_message_size: 10MiB
        host: "localhost:9000"
      output.elasticsearch:
        hosts: '${elasticsearch-master.db:9200}'