---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: db
  labels:
    name: db
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: watch
  labels:
    name: watch
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: log
  labels:
    name: log
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vault
  labels:
    name: vault
---